# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prototype.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.scheduleLayout = QtWidgets.QGridLayout()
        self.scheduleLayout.setObjectName("scheduleLayout")
        self.activatedView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activatedView.sizePolicy().hasHeightForWidth())
        self.activatedView.setSizePolicy(sizePolicy)
        self.activatedView.setMaximumSize(QtCore.QSize(16777215, 60))
        self.activatedView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activatedView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.activatedView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.activatedView.setObjectName("activatedView")
        self.scheduleLayout.addWidget(self.activatedView, 2, 1, 1, 2)
        self.restoreButtonLayout = QtWidgets.QHBoxLayout()
        self.restoreButtonLayout.setObjectName("restoreButtonLayout")
        self.restoreAllButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restoreAllButton.sizePolicy().hasHeightForWidth())
        self.restoreAllButton.setSizePolicy(sizePolicy)
        self.restoreAllButton.setMinimumSize(QtCore.QSize(100, 60))
        self.restoreAllButton.setObjectName("restoreAllButton")
        self.restoreButtonLayout.addWidget(self.restoreAllButton)
        self.scheduleLayout.addLayout(self.restoreButtonLayout, 0, 1, 1, 2)
        self.scheduleView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scheduleView.sizePolicy().hasHeightForWidth())
        self.scheduleView.setSizePolicy(sizePolicy)
        self.scheduleView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scheduleView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scheduleView.setObjectName("scheduleView")
        self.scheduleLayout.addWidget(self.scheduleView, 6, 1, 1, 2)
        self.gridLayout.addLayout(self.scheduleLayout, 0, 5, 9, 1)
        self.sideLayout = QtWidgets.QGridLayout()
        self.sideLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.sideLayout.setSpacing(10)
        self.sideLayout.setObjectName("sideLayout")
        self.addEventButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addEventButton.sizePolicy().hasHeightForWidth())
        self.addEventButton.setSizePolicy(sizePolicy)
        self.addEventButton.setObjectName("addEventButton")
        self.sideLayout.addWidget(self.addEventButton, 12, 0, 1, 2)
        self.dummy1Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dummy1Button.sizePolicy().hasHeightForWidth())
        self.dummy1Button.setSizePolicy(sizePolicy)
        self.dummy1Button.setObjectName("dummy1Button")
        self.sideLayout.addWidget(self.dummy1Button, 15, 0, 1, 2)
        self.language1Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language1Button.sizePolicy().hasHeightForWidth())
        self.language1Button.setSizePolicy(sizePolicy)
        self.language1Button.setObjectName("language1Button")
        self.sideLayout.addWidget(self.language1Button, 19, 1, 1, 1)
        self.language5Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language5Button.sizePolicy().hasHeightForWidth())
        self.language5Button.setSizePolicy(sizePolicy)
        self.language5Button.setObjectName("language5Button")
        self.sideLayout.addWidget(self.language5Button, 21, 1, 1, 1)
        self.language0Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language0Button.sizePolicy().hasHeightForWidth())
        self.language0Button.setSizePolicy(sizePolicy)
        self.language0Button.setObjectName("language0Button")
        self.sideLayout.addWidget(self.language0Button, 19, 0, 1, 1)
        self.dummy0Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dummy0Button.sizePolicy().hasHeightForWidth())
        self.dummy0Button.setSizePolicy(sizePolicy)
        self.dummy0Button.setObjectName("dummy0Button")
        self.sideLayout.addWidget(self.dummy0Button, 13, 0, 1, 2)
        self.language3Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language3Button.sizePolicy().hasHeightForWidth())
        self.language3Button.setSizePolicy(sizePolicy)
        self.language3Button.setObjectName("language3Button")
        self.sideLayout.addWidget(self.language3Button, 20, 1, 1, 1)
        self.language4Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language4Button.sizePolicy().hasHeightForWidth())
        self.language4Button.setSizePolicy(sizePolicy)
        self.language4Button.setObjectName("language4Button")
        self.sideLayout.addWidget(self.language4Button, 21, 0, 1, 1)
        self.language2Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language2Button.sizePolicy().hasHeightForWidth())
        self.language2Button.setSizePolicy(sizePolicy)
        self.language2Button.setObjectName("language2Button")
        self.sideLayout.addWidget(self.language2Button, 20, 0, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName("searchButton")
        self.sideLayout.addWidget(self.searchButton, 9, 0, 1, 2)
        self.dummy2Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dummy2Button.sizePolicy().hasHeightForWidth())
        self.dummy2Button.setSizePolicy(sizePolicy)
        self.dummy2Button.setObjectName("dummy2Button")
        self.sideLayout.addWidget(self.dummy2Button, 16, 0, 1, 2)
        self.dayDisplayLayout = QtWidgets.QHBoxLayout()
        self.dayDisplayLayout.setObjectName("dayDisplayLayout")
        self.prevDayButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevDayButton.sizePolicy().hasHeightForWidth())
        self.prevDayButton.setSizePolicy(sizePolicy)
        self.prevDayButton.setObjectName("prevDayButton")
        self.dayDisplayLayout.addWidget(self.prevDayButton)
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.dayDisplayLayout.addWidget(self.dateLabel)
        self.nextDayButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextDayButton.sizePolicy().hasHeightForWidth())
        self.nextDayButton.setSizePolicy(sizePolicy)
        self.nextDayButton.setObjectName("nextDayButton")
        self.dayDisplayLayout.addWidget(self.nextDayButton)
        self.sideLayout.addLayout(self.dayDisplayLayout, 7, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.displayedCalendarLabel = QtWidgets.QLabel(self.centralwidget)
        self.displayedCalendarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayedCalendarLabel.setObjectName("displayedCalendarLabel")
        self.gridLayout_2.addWidget(self.displayedCalendarLabel, 0, 1, 1, 1)
        self.prevMonthButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevMonthButton.sizePolicy().hasHeightForWidth())
        self.prevMonthButton.setSizePolicy(sizePolicy)
        self.prevMonthButton.setMinimumSize(QtCore.QSize(0, 40))
        self.prevMonthButton.setObjectName("prevMonthButton")
        self.gridLayout_2.addWidget(self.prevMonthButton, 0, 0, 1, 1)
        self.nextMonthButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextMonthButton.sizePolicy().hasHeightForWidth())
        self.nextMonthButton.setSizePolicy(sizePolicy)
        self.nextMonthButton.setMinimumSize(QtCore.QSize(0, 40))
        self.nextMonthButton.setObjectName("nextMonthButton")
        self.gridLayout_2.addWidget(self.nextMonthButton, 0, 2, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_2.addWidget(self.calendarWidget, 1, 0, 1, 3)
        self.sideLayout.addLayout(self.gridLayout_2, 1, 0, 2, 2)
        self.todayButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.todayButton.sizePolicy().hasHeightForWidth())
        self.todayButton.setSizePolicy(sizePolicy)
        self.todayButton.setObjectName("todayButton")
        self.sideLayout.addWidget(self.todayButton, 8, 0, 1, 2)
        self.gridLayout.addLayout(self.sideLayout, 0, 1, 9, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.restoreAllButton.setText(_translate("MainWindow", "Restore All"))
        self.addEventButton.setText(_translate("MainWindow", "Add Event"))
        self.dummy1Button.setText(_translate("MainWindow", "Dummy 1"))
        self.language1Button.setText(_translate("MainWindow", "Russian"))
        self.language5Button.setText(_translate("MainWindow", "Italian"))
        self.language0Button.setText(_translate("MainWindow", "English"))
        self.dummy0Button.setText(_translate("MainWindow", "Dummy 0"))
        self.language3Button.setText(_translate("MainWindow", "Japanese"))
        self.language4Button.setText(_translate("MainWindow", "French"))
        self.language2Button.setText(_translate("MainWindow", "German"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.dummy2Button.setText(_translate("MainWindow", "Dummy 2"))
        self.prevDayButton.setText(_translate("MainWindow", "Prev Day"))
        self.dateLabel.setText(_translate("MainWindow", "Current Date"))
        self.nextDayButton.setText(_translate("MainWindow", "Next Day"))
        self.displayedCalendarLabel.setText(_translate("MainWindow", "Month / Year"))
        self.prevMonthButton.setText(_translate("MainWindow", "Prev Month"))
        self.nextMonthButton.setText(_translate("MainWindow", "Next Month"))
        self.todayButton.setText(_translate("MainWindow", "Today"))

